FROM node:18-alpine 
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm ci
COPY . .
COPY .env .env
# COPY src/solana/nds_transaction_main.json ./src/solana/nds_transaction.json
RUN npm run build
EXPOSE 4875
CMD ["npm","run","serve"]
